<?php

declare(strict_types=1);

use Illuminate\Database\QueryException;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\System\Page;
use App\Models\System\Role;
use App\Models\System\User;

/**
 * PagesTableSeeder Seeder
 *
 * @author Antonio Vargas <localhost.80@gmail.com>
 * @copyright 2020 MdRepTime, LLC
 */
class PagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $site = site(config('app.base_domain'));
        $user = User::role(Role::SUPER_ADMIN)->first();
        $pages = [
            [
                'title'     => 'Company',
                'content'   => '<p>As we transcend further into the 21st century, it seems that almost every faucet of life has been disrupted by the digital world. The best digital solutions almost give us back what we value the most… TIME!</p><p>Office staff can use extra time to focus on caring for their patients and improving outcomes. Representatives can spend less time setting appointments and more time conversing with providers.</p><p>We knew that there had to be a better way to create more meaningful visits from industry representatives. Through a survey, we found that offices can spend as much as 10 hours a week managing representatives! There is so much time wasted on both sides trying to set up meetings/ managing industry representatives, so we thought "Lets change that!"</p><p>Insert MD REP TIME. A digital communication platform that connects medical providers to industry representatives.</p><p>Our goal is simple: Provide you a platform that simplifies your daily interactions and gives you back your time.</p>'
            ],
            [
                'title'     => 'Representatives',
                'content'   => '<ul><li>Become discoverable in rep database.</li><li>Have access to the provider’s calendar.</li><li>Request meetings based on availability and interest level.</li><li>Easy messaging platform (no more texting).</li><li>More meaningful meetings=Increase in sales.</li><li>Automatically track office staff for Sunshine Act reporting.</li><li>Less time setting meetings -> More time selling.</li></ul>',
                'image'     => public_path('images/rep_graphic.png'),
            ],
            [
                'title'     => 'Offices',
                'content'   => '<ul><li>Completely free software.</li><li>Simplify rep appointments to online platform.</li><li>Search rep database for contact information.</li><li>Easy messaging platform (no more texting).</li><li>Ensure reps are compliant with office rules.</li><li>Sign up in 2 minutes!</li></ul>',
                'image'     => public_path('images/office_graphic.png'),
            ],
            [
                'title'     => 'Privacy',
                'content'   => "<h3>Privacy Policy Notice</h3>
                                <p>Effective January 1, 2020</p>
                                <p>
                                MD REP TIME LLC (“MD REP TIME”, “we”, or “us”) recognizes the importance of privacy.
                                We want you to feel confident using our services, and this privacy notice (“Privacy Notice” or “Notice”)
                                is to help you understand and describe how we collect, use, and disclose your information.
                                </p>
                                <p>This Notice describes the following:</p>
                                <ul>
                                <li>What information we collect and how it is collected;</li>
                                <li>How we use the information;</li>
                                <li>With whom we may share information;</li>
                                <li>Legal basis for processing the information;</li>
                                <li>Your rights and choices;</li>
                                <li>Security and storage of the information;</li>
                                <li>Third-party websites;</li>
                                <li>Users outside the United States;</li>
                                <li>CCPA Compliance;</li>
                                <li>Changes to the Notice; and</li>
                                <li>Contacting MD REP TIME.</li>
                                </ul>
                                <p>
                                Throughout this document, we will use a few terms to describe various products and roles.
                                All of the text, data, information, software, graphics, photographs and more that we and our
                                affiliates may make available to you, plus our websites and any services, plug-ins, software,
                                or applications that we may provide all together constitute the MD REP TIME “Website.”
                                MD REP TIME “Users” are the people who have created a MD REP TIME account, and “MD REP TIME Invitees”
                                are people who have scheduled a meeting with a MD REP TIME User but may or may not have registered with
                                MD REP TIME. A MD REP TIME “Viewer” is a person who visits the MD REP TIME Website but may or may not be a
                                MD REP TIME User or MD REP TIME Invitee.
                                </p>
                                <p>
                                Any terms defined in the Terms of Use, End User License Agreement, and
                                Data Processing Addendum and not otherwise defined in this Privacy Notice are hereby adopted by reference in this Privacy Notice.
                                </p>
                                <h4>Educational Use</h4>
                                <p>
                                For educational service providers and schools, please see our FERPA and COPPA Privacy Policy and Notice.
                                </p>
                                <h4>Information We Collect</h4>
                                <p>We collect information about you directly from you and automatically through your use of our Website.
                                We may combine information automatically collected with other information that we have collected about you
                                including from publicly available sources.
                                </p>
                                <p>In order to help you protect yourself and your information, we encourage you to
                                provide only that information that is necessary for using our Website. For example,
                                to schedule a meeting you may only need to provide us with a name, email address, date, and time.
                                </p>
                                <p>MD REP TIME is not directed to children under thirteen (18) years of age and we do not knowingly collect
                                Personal Information from children under 18. If we discover that a child under 18 has provided us with Personal Information,
                                we will promptly delete such Personal Information from our systems.
                                </p>
                                <h4>Information You Provide Voluntarily</h4>
                                <p>MD REP TIME collects the following information, either directly from MD REP TIME Users,
                                Invitees, or Viewers, or through third-parties regarding Users, Invitees, or Viewers.
                                </p>
                                <ul>
                                <li>Appointment Information. A MD REP TIME User, Invitee, or a third-party may voluntarily give us certain information.
                                This can include names, email addresses, and phone numbers; email addresses of other people; the subject of the meeting;
                                and any other information provided to us or as required by the MD REP TIME User upon scheduling,
                                pursuant to the MD REP TIME Terms of Use. If you receive an invitation from a MD REP TIME User but do not wish to
                                become a MD REP TIME User, please contact the MD REP TIME User who sent the invitation through other means to set up your meeting.
                                </li>
                                <li>Calendar Information. A MD REP TIME User may connect their calendar with MD REP TIME.
                                Our calendar integration only checks the duration and free/busy status of the events in your calendar
                                so that we don’t book you when you’re busy. We never store who you are meeting with, their email address,
                                the meeting title, or any other details about the appointments in your connected calendar.
                                </li>
                                <li>Billing Information. If you purchase a subscription to MD REP TIME, our third-party payment processors will collect
                                and store your billing address and credit card information. We store the last four digits of your credit card number,
                                card type, and the expiration date
                                </li>
                                </ul>
                                <h4>Information Collected Automatically</h4>
                                <p>Like many websites, we and our Service Providers use Cookies, web beacons, and other technologies to receive
                                and store certain types of information when you interact with us through your computer or mobile device subject to
                                your opt-out preferences (see Your Rights and Choices section below). Using these technologies helps us customize
                                your experience with our Website, improve your experience, and tailor marketing messages. Here are some of the
                                types of information we collect:
                                </p>
                                <ul>
                                <li>Log & Device data. When you use MD REP TIME, our servers automatically record information (“log data”), including information that your browser sends whenever you visit our Website. This log data may include the web address you came from or are going to, your device model, operating system, browser type, unique device identifier, IP address, mobile network carrier, and time zone or location. Whether we collect some or all of this information often depends on what type of device you’re using and its settings. For example, different types of information are available depending on whether you’re using a Mac or PC, or an iPhone or an Android phone. To learn more about what information your device makes available to us, please check the policies of your device manufacturer or software provider.</li>
                                <li>Cookie data. Depending on how you’re accessing our services and subject to your opt-out preferences, we may use “Cookies” (a small text file sent by your computer each time you visit our Website, unique to your MD REP TIME account or your browser) or similar technologies to record log data. When we use Cookies, we may use ‘session’ Cookies (that last until you close your browser) or ‘persistent’ Cookies (that last until you or your browser deletes them). For example, we may use Cookies to keep you logged into MD REP TIME. Some of the Cookies we use are associated with your MD REP TIME account (including personal information about you, such as the email address you gave us), and other Cookies are not.</li>
                                <li>Other Web Site Analytics Services. Subject to your opt-out preferences (see ‘Your Rights and Choices’ below), we use third-party Service Providers such as Google Analytics to provide certain analytics and Viewer interactions services to MD REP TIME in connection with our operation of our Website, including the collection and tracking of certain data and information regarding the characteristics and activities of visitors to MD REP TIME. You may opt-out of relevant cookies using opt-out features on their respective websites</li>
                                </ul>
                                <h4>How We Use Your Information</h4>
                                <p>We may use information that we collect about you, including Personal Data, to:</p>
                                <ul>
                                <li>Provide the MD REP TIME Service. We will use your information to provide our Website to you; including facilitating scheduling; managing your account; responding to your inquiries; and for other customer service and support purposes. We use the payment information you provide to us in order to alert you of past, current, and upcoming charges, to allow us to present the billing history to you on your billing page in the Website, and to perform internal financial processes, such as looking at the status of a credit card charge. In the event of a credit card dispute, we also share account information with your bank to verify the legitimacy of a charge.</li>
                                <li>Understand and improve our products. We will perform research and analysis about your use of, or interest in, our products, services, or content, or products, services or content offered by others. We do this to help make our products better and to develop new products.</li>
                                <li>
                                Communicate with you.
                                <ul>
                                <li>Service related communications. We may send you service and administrative emails to ensure the service is working properly. We will also email you regarding your calendar appointments. These messages are considered part of the service and you may not opt out of these messages.</li>
                                <li>Promotional. Subject to your opt-out preference, we may send you emails about new product features or other news about MD REP TIME or on topics we think would be relevant to you. You may opt out of receiving these communications at any time. Visit the ‘Your Rights and Choices’ section below. For MD REP TIME Invitees, please be assured that we do not use the email addresses that you enter to schedule a meeting with a MD REP TIME User to send any type of direct marketing.</li>
                                <li>Responding to your requests. We will also use your information to respond to your questions or comments.</li>
                                <li>Administrative. We may contact you to inform you about changes in your services, our service offering and other important service-related notices, such as changes to the Notice or about security or fraud notices.</li>
                                </ul>
                                </li>
                                <li>Protecting Rights and Interests. We will use your information to protect our rights and interests as well as the rights and interests of our Users and any other person, as well as to enforce this Notice or our Terms of Use.</li>
                                <li>Legal Compliance. We may use your information to comply with applicable legal or regulatory obligations, including complying with requests from law enforcement or other governmental authorities, or in legal proceedings involving MD REP TIME.</li>
                                <li>Other. We also may use your information to manage our business or perform functions as otherwise described to you at the time of collection subject to your consent.</li>
                                </ul>
                                <h4>With Whom We May Share Your Information</h4>
                                <p>We do not sell your information to any third parties or disclose it in exchange for money or other valuable consideration. We do not share your Personal Data with others except as indicated within this Notice, or when we inform you and give you an opportunity to opt-out of having your Personal Data shared.</p>
                                <p>We will never use Invitee data to send direct marketing via emails, SMS, physical mailings, or other similar communication channels to advertise or promote the use of our product and services or those of a third-party.</p>
                                <p>We may share information we collect about you, including Personal Data, in the following ways:</p>
                                <ul>
                                <li>With third-party Service Providers, agents, contractors, or government entities. We use other companies, agents or contractors (“Service Providers”) to perform services on our behalf or to assist us with providing services to you: We may engage Service Providers to process credit card transactions or other payment methods. We may also engage Service Providers to provide services such as monitoring and developing MD REP TIME services; aiding in communications, infrastructure, and IT services; customer service; debt collection; analyzing and enhancing data. These Service Providers may have access to your personal or other information in order to provide these functions. In addition, some of the above-listed types of information that we request may be collected by third-party Service Providers on our behalf. We may share information with Service Providers and government entities for legal, security, and safety purposes. This includes sharing information in order to enforce policies or contracts, address security breaches, and assist in the investigation of fraud, security issues, or other concerns. We require Service Providers to agree to take reasonable steps to keep the Personal Data that we provide to them secure. We do not authorize them to use or disclose your Personal Data except in connection with providing their services.</li>
                                <li>Affiliates.<br>We may disclose information to current or future affiliates or subsidiaries for research, marketing, and other purposes consistent with this Privacy Notice. We may share your data if we believe that disclosure is reasonably necessary to comply with a law, regulation, legal, or governmental request; to respond to a subpoena, court order, warrant, or other legal process; to enforce applicable Terms of Use or this Notice, including investigation of potential violations thereof; to protect the safety, rights, or property of the public, any person, or MD REP TIME; to detect, prevent, or otherwise address, security or technical issues, illegal, or suspected illegal activities (including fraud); or as evidence in litigation in which we are involved, as part of a judicial or regulatory proceeding. If you are using MD REP TIME as a paid member of an organization or using your organization’s email domain (thereby representing yourself as a member of the organization), we may share your email address and plan information with an authorized agent of your company upon request in order for them to administer the account for the company.</li>
                                </ul>
                                <h4>Your Rights and Choices</h4>
                                <ul>
                                <li>Account. In order to keep your Personal Data accurate and complete, you can log in to review and update your account information, including contact and billing information, via your account settings page. You may also contact us to request information about the personal data we have collected from you and to request the correction, modification or deletion of such Personal Data. We will do our best to honor your requests subject to any legal and contractual obligations. If you would like to make a request, cancel your account or request we delete or no longer use your account information to provide you our Website, contact us at <a href=\"mailto:support@mdreptime.com\">support@mdreptime.com</a> or the address set forth at the end of this Notice. Subject to applicable law, we will retain and use your account information only as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements</li>
                                <li>E-mail. As described above, if you do not wish to receive promotional emails from us, you may opt out at any time by following the opt-out link contained in the email itself. Please note that it may take up to ten (10) days to process your request. Please also note that if you opt out of receiving marketing communications from us, we may continue to send to you service-related emails which are not available for opt-out. If you do not wish to receive any service-related emails from us, you have the option to delete your account.</li>
                                <li>Cookies. You may also refrain from providing or may withdraw your consent for Cookies via your browser settings and via limited opt-out functions within MD REP TIME. Your browser’s help function should contain instructions on how to set your computer to accept all Cookies, to notify you when a Cookie is issued, or to not receive Cookies at any time. Please keep in mind that Cookies are required to authenticate MD REP TIME Users as well as perform some actions within MD REP TIME (such as to pay for an event as an Invitee via MD REP TIME), so in order to use the Website, Cookies are often required.</li>
                                <li>Third Party Analytics Services. Some of the services used provide the ability to opt-out. You may opt out of Google Analytics’ services using the Opt-Out feature on their website. The Google Analytics service is provided by Google Inc. You can opt-out from Google Analytics service from using your information by installing the Google Analytics Opt-out Browser tool: https://tools.google.com/dlpage/gaoptout.For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: https://www.google.com/policies/privacy. You may opt out of Clearbit’s services using their opt-out feature: https://claim.clearbit.com/claim. For more information on the privacy practices of Clearbit, please visit their privacy policy: https://clearbit.com/privacy. You may opt out of Facebook Pixel’s services using their opt-out feature: https://www.facebook.com/help/568137493302217. For more information on the privacy practices of Facebook, please visit their Data Policy: https://www.facebook.com/about/privacy.</li>
                                <li>Additional Rights. Subject to local law, you may have additional rights under the laws of your jurisdiction regarding your personal data, such as the right to complain to your local data protection authority.</li>
                                </ul>
                                <h4>Security and Storage of Information</h4>
                                <p>We have taken reasonable steps to help protect the personal information we collect.</p>
                                <p>MD REP TIME takes the security of your personal data very seriously. We work hard to protect the personal data that you provide from loss, misuse, and unauthorized access, or disclosure. Given the nature of communications and information processing technology, there is no guarantee that personal data will be absolutely safe from access, alteration, or destruction by a breach of any of our physical, technical, and managerial safeguards.</p>
                                <p>You should take steps to protect against unauthorized access to your device and account by, among other things, choosing a unique and complex password that nobody else knows or can easily guess and keeping your log-in and password private. We are not responsible for any lost, stolen, or compromised passwords or for any activity on your account via unauthorized password activity.</p>
                                <p>We retain the personal data we collect for so long as is reasonably necessary to fulfill the purposes for which the data was collected, to perform our contractual and legal obligations, and for any applicable statute of limitations periods for the purposes of bringing and defending claims.</p>
                                <h4>Third-Party Links</h4>
                                <p>Our Website may contain links to third-party websites and applications. Subject to your opt-out preferences (see Your Rights and Choices), we may also use third-party advertisers, ad networks, and other advertising, marketing, and promotional companies, to serve advertisements on our Website. Any access to and use of such linked websites and applications is not governed by this Notice but instead is governed by the privacy policies of those third parties. We do not endorse these parties, their content, or any products and services they offer, and we do not endorse these parties, their content, or any products and services they offer, and we are not responsible for the information practices of such third-party websites or applications.</p>
                                <h4>Users Outside the USA</h4>
                                <p>Our application and database servers are located with Amazon Cloud Services in the United States. Amazon Cloud Services has certified with the Department of Commerce that it adheres to the Privacy Shield Principles under the EU-U.S. Privacy Shield framework and the Swiss-U.S. Privacy Shield framework.</p>
                                <p>If you are an individual located in the European Economic Area, the United Kingdom, Canada or another jurisdiction outside of the United States with laws and regulations governing personal data collection, use, and disclosure that differ from United States laws, please be aware that information we collect (including through the use of methods such as Cookies and other web technologies) will be processed and stored in the United States or in other countries where we or our third-party Service Providers have operations. By submitting your personal data to MD REP TIME and using MD REP TIME, you expressly consent to have your personal data transferred to, processed, and stored in the United States or another jurisdiction which may not offer the same level of privacy protection as those in the country where you reside or are a citizen.</p>
                                <p>In connection with the operation of its Website, MD REP TIME may transfer your personal data to various locations, which may include locations both inside and outside of the European Economic Area. MD REP TIME is in the process of submitting our certification of compliance with the EU-U.S. and Swiss-U.S. Privacy Shield with respect to the personal data of Users of the MD REP TIME who are residents of the EU, EEA or Switzerland that we receive and process through MD REP TIME. We adhere to the Privacy Shield Principles of notice, choice, onward transfer, security, data integrity, access, liability and enforcement for individuals in participating European countries whose personal data is processed through MD REP TIME and will certify accordingly to the Department of Commerce. We may also process personal data submitted relating to individuals in Europe via the European Union Standard Contractual Clauses.</p>
                                <h4>Do Not Track</h4>
                                <p>We do not currently recognize or respond to browser-initiated Do Not Track signals as there is no consistent industry standard for compliance.</p>
                                <h4>Dispute Resolution</h4>
                                <p>For any complaints that cannot be resolved with MD REP TIME directly, MD REP TIME has chosen to utilize the JAMS Privacy Shield Program in relation to such unresolved complaints (as further described in the Principles). As further explained in the Privacy Shield Framework Annex I, a binding arbitration option will also be made available to you in order to address residual complaints not resolved by any other means.</p>
                                <h4>Changes to this Notice</h4>
                                <p>This Notice is current as of the Effective Date set forth above. This Notice may change if there is a material change to the way information is handled at MD REP TIME, or to clarify our Notice or adjust clerical errors. If any changes are made, we’ll post them on this page, so please be sure to check back periodically. If you continue to use MD REP TIME after those changes are in effect, you agree to the revised Notice.</p>
                                <h4>Contacting Us</h4>
                                <p>If you have any questions or comments about this Notice, please contact us at <a href=\"mailto:support@mdreptime.com\">support@mdreptime.com</a>. For questions or comments outside of the Privacy Notice, please contact us at <a href=\"mailto:support@mdreptime.com\">support@mdreptime.com</a></p>
                                <h4>Privacy Notice for California Residents</h4>
                                <p>Effective date: December 31, 2019</p>
                                <p>This Privacy Notice for California Residents (“California Notice”) supplements the MD REP TIME Privacy Notice. It applies solely to MD REP TIME Users, Viewers, and Invitees who live in the State of California (“California Residents”). MD REP TIME adopts this notice to comply with the California Consumer Privacy Act of 2019 and any subsequent amendments (“CCPA”). All terms used in this California Notice have the same meaning as when used in the CCPA. For frequently asked questions related to the CCPA please view our CCPA FAQs Page.</p>
                                <h4>Information MD REP TIME May Collect Regarding California Residents</h4>
                                <p>MD REP TIME collects information that identifies, relates to, describes, references, is capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular consumer or device (“Personal Information”). In particular, our Website may have collected the following categories of Personal Information from California Resident Users, Invitees, and Viewers within the last twelve months, for the purpose of establishing, maintaining, and supporting the services that we provide through our Website:</p>
                                <ul>
                                <li>A. Identifiers: real name; alias; email address; internet protocol address</li>
                                <li>B. Personal Information categories listed in Cal. Civ. Code Sec. 1798.80(e): Real name; phone number.</li>
                                <li>C. Commercial information: Purchase records regarding MD REP TIME products.</li>
                                <li>D. Internet or other similar network activity: Data on Viewers’ interaction with the MD REP TIME Website.</li>
                                </ul>
                                <p>MD REP TIME Obtains the Categories of Personal Information Listed Above from the Following Categories of Sources</p>
                                <ul>
                                <li>Directly from our Users and Invitees.</li>
                                <li>Indirectly from our Users and Invitees.</li>
                                <li>Directly and indirectly from activity on our Website.</li>
                                <li>From third parties that interact with us in connection with the services we perform</li>
                                </ul>
                                <h4>How California Resident Personal Information May Be Used</h4>
                                <p>We may use or disclose the Personal Information we collect for one or more of the following business purposes:</p>
                                <ul>
                                <li>To fulfill or meet the reason for which the information is provided.</li>
                                <li>To provide you with information or services that you request from us.</li>
                                <li>To provide you with email alerts and other notices concerning our services, or news that may be of interest to you.</li>
                                <li>To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collections.</li>
                                <li>To improve our Website.</li>
                                <li>For testing, research, analysis and service development.</li>
                                <li>As necessary or appropriate to protect MD REP TIME and our Users.</li>
                                <li>To respond to law enforcement requests and as required by applicable law, court order, or governmental regulations.</li>
                                <li>As described to you when your Personal Information was collected, or as otherwise set forth in the CCPA.</li>
                                <li>To evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Information held by MD REP TIME is among the assets transferred. MD REP TIME will not collect additional categories of Personal Information or use the Personal Information we collect for materially different, unrelated, or incompatible purposes without providing you notice.</li>
                                </ul>
                                <h4>Sharing Personal Information</h4>
                                <p>We may disclose your Personal Information to a third-party for a business purpose. When we disclose Personal Information for a business purpose, we enter a contract that describes the purpose and requires the recipient to both keep that Personal Information confidential and not use it for any purpose except performing your contract.</p>
                                <p>We disclose your Personal Information for a business purpose to the following categories of third parties:</p>
                                <ul>
                                <li>Service Providers.</li>
                                <li>Third parties to whom you or your agents authorize us to disclose your Personal Information in connection with the services we provide to you.</li>
                                <li>Government representatives as required by law</li>
                                </ul>
                                <p>In the preceding twelve (12) months, we have not sold any Personal Information.</p>
                                <h4>Access to Specific Information and Data Portability Rights</h4>
                                <p>You have the right to request that we disclose certain information to you about our collection and use of your Personal Information over the past 12 months. Once we receive and confirm your verifiable consumer request, we will disclose to you:</p>
                                <ul>
                                <li>The categories of Personal Information we collected about you.</li>
                                <li>The categories of sources for the Personal Information we collected about you.</li>
                                <li>Our business or commercial purpose for collecting or selling that Personal Information.</li>
                                <li>The categories of third parties with whom we share that Personal Information.</li>
                                <li>The specific pieces of Personal Information that we have collected about you.</li>
                                </ul>
                                <h4>Deletion Request Rights</h4>
                                <p>You have the right to request that we delete any of your Personal Information that we have collected from you and retained, subject to certain exceptions. All deletion requests will be managed in accordance with MD REP TIME Deletion Procedures. Deletion requests should be sent to <a href=\"mailto:support@mdreptime.com\">support@mdreptime.com</a>. Once we receive and confirm your verifiable request, we will delete (and direct our Service Providers to delete) your Personal Information from our records, unless an exception applies.</p>
                                <p>We may deny your deletion request if retaining the information is necessary for us or our service providers to:</p>
                                <ul>
                                <li>Complete the transaction for which we collected the Personal Information, provide a service that you requested, take actions reasonably anticipated within the context of our ongoing business relationship with you, or otherwise perform our contract with you.</li>
                                <li>Detect security incidents, protect against malicious, deceptive, fraudulent, or illegal activity, or prosecute those responsible for such activities.</li>
                                <li>Debug software to identify and repair errors that impair existing intended functionality.</li>
                                <li>Comply with the California Electronic Communications Privacy Act.</li>
                                <li>Enable solely internal uses that are reasonably aligned with consumer expectations based on your relationship with us.</li>
                                <li>Comply with a legal obligation.</li>
                                <li>Otherwise lawfully use that information in compatibility with the context in which you provided it.</li>
                                </ul>
                                <h4>Exercising Access, Data Portability, and Deletion Rights</h4>
                                <p>To exercise the access, data portability, and deletion rights described above, please submit a verifiable consumer request to us by reaching out to <a href=\"mailto:support@mdreptime.com\">support@mdreptime.com</a>.</p>
                                <p>Only you or a person registered with the California Secretary of State that you authorize to act on your behalf may make a verifiable consumer request related to your Personal Information. You may also make a verifiable consumer request on behalf of your minor child. You may only make a verifiable California Resident request for access or data portability twice within a 12-month period.</p>
                                <p>The request must:</p>
                                <ul>
                                <li>Provide sufficiently detailed information to allow MD REP TIME to reasonably verify that you are the person to whom the requested Personal Information pertains or their authorized representative.</li>
                                <li>Include sufficient detail to allow us to properly understand, evaluate, and respond to it.</li>
                                <li>We cannot respond to your request or provide you with Personal information if we cannot verify your identity or authority to make the request and confirm the Personal Information relates to you.</li>
                                <li>Making a verifiable consumer request does not require you to create an account with us.</li>
                                <li>MD REP TIME will only use Personal Information provided in a verifiable consumer request to verify the requestor's identity or authority to make the request.</li>
                                </ul>
                                <h4>Response Timing and Format</h4>
                                <p>We will attempt to respond to California Resident requests in as timely a fashion as possible. In the event of delays over 60 days, we will inform you of the reason and extension period in writing. If you have an account with us, we will deliver our written response to that account. Any disclosures we provide will only cover the 12-month period preceding the verifiable receipt of a California Resident’s request. The response we provide will explain the reasons we cannot comply with a request, if applicable.</p>
                                <p>We do not charge a fee to process or respond to your verifiable consumer request unless it is excessive, repetitive, or manifestly unfounded. If we determine that the request warrants a fee, we will tell you why we made that decision and provide you with a cost estimate before fulfilling your request.</p>
                                <h4>Non-Discrimination</h4>
                                <p>In accordance with the CCPA’s requirements, we will not discriminate against you for exercising any of your CCPA rights.</p>
                                <h4>Changes to Our Privacy Notice</h4>
                                <p>We reserve the right to amend this privacy notice at our discretion and at any time and will notify you by email or through a notice on our Website homepage.</p>
                                <h4>Contact Information</h4>
                                <p>If you have any questions or comments about this notice, our Privacy Notice, the ways in which we collect and use your Personal Information, your choices and rights regarding such use, or wish to exercise your rights under California law, please do not hesitate to contact us at: <a href=\"mailto:support@mdreptime.com\">support@mdreptime.com</a>.</p>"

            ],
            [
                'title'     => 'Terms',
                'content'   => "<p>Effective January 1, 2020</p>
                                <p>Thanks for using MD REP TIME. These Terms of Use (“Terms” or \"Agreement\") are a legal agreement between you and MD REP TIME, LLC (“MD REP TIME,” “we,” “our,” or “us”) and govern your use of all the text, data, information, software, graphics, photographs and more that we and our affiliates may make available to you (all of which we refer to as “Materials”), including our websites and any services, plug-ins, software or other Downloadable Tools (as defined below) that we may provide through any of our websites (the “Platform” and together with the Materials, this “Website”). The terms \"us\" or \"we\" or \"our\" refer to MD REP TIME, the owner of this Website. MD REP TIME “Users” are the people who have created a MD REP TIME account, and MD REP TIME “Invitees” are people who have scheduled a meeting with a MD REP TIME User but may or may not have registered with MD REP TIME. A MD REP TIME “Viewer” is a person who visits the MD REP TIME Website but may or may not be a MD REP TIME User or MD REP TIME Invitee.</p>
                                <p>If you are entering into these Terms on behalf of a company or other organization, you hereby represent and warrant that you are authorized to enter into these Terms on behalf of such company or other organization.</p>
                                <p>READ THESE TERMS CAREFULLY BEFORE BROWSING THIS WEBSITE. USING THIS WEBSITE INDICATES THAT YOU HAVE BOTH READ AND ACCEPT THESE TERMS. YOU CANNOT USE THIS WEBSITE IF YOU DO NOT ACCEPT THESE TERMS. THESE TERMS CONTAIN A DISPUTE RESOLUTION AND ARBITRATION PROVISION, INCLUDING A CLASS ACTION WAIVER THAT AFFECTS YOUR RIGHTS UNDER THESE TERMS AND WITH RESPECT TO DISPUTES YOU MAY HAVE WITH MD REP TIME.</p>
                                <p>IF YOU ARE A MD REP TIME USER, VIEWER, OR INVITEE LOCATED IN THE EUROPEAN ECONOMIC AREA, SWITZERLAND, OR UNITED KINGDOM, THE DATA PROCESSING ADDENDUM ACCOMPANIES THESE TERMS AND SETS FORTH OTHER TERMS OF OUR AGREEMENT THAT APPLY SOLELY TO THE EXTENT ANY INFORMATION YOU PROVIDE TO MD REP TIME INCLUDES PERSONAL DATA OF INDIVIDUALS LOCATED IN THE EUROPEAN ECONOMIC AREA, SWITZERLAND, AND THE UNITED KINGDOM.</p>
                                <h4>SCOPE</h4>
                                <p>MD REP TIME’s Website facilitates online scheduling of appointments. You may access and use the Website in accordance with these Terms. Please note that these Terms govern your use of the Website, including, but not limited to, the process through which your Invitees schedule appointments with you.</p>
                                <p>When using the features of the Website you are subject to any agreements, policies or guidelines applicable to such features that may be posted from time to time. All such agreements, policies or guidelines, including the Privacy Policy, the End User License Agreement and the Data Processing Addendum (as applicable) are hereby incorporated by reference into these Terms.</p>
                                <h4>GENERAL USE</h4>
                                <p>We invite you to use this Website for your individual purposes and not for the purposes of reselling (\"Permitted Purposes\") – enjoy!</p>
                                <p>Subject to these Terms, we grant you a limited, personal, non-exclusive and non-transferable license to use and to display the Materials and a limited, personal, non-exclusive and non-transferable right to access and use the Website following the set-up of a Free Account or Paid Account as set forth below. You have no other rights in the Website and you may not modify, edit, copy, reproduce, create derivative works of, reverse engineer, alter, enhance, or in any way exploit any portion of the Website in any manner. If you make copies of any portion of this Website while engaging in Permitted Purposes then we ask that you be sure to keep on these copies all of our copyright and other proprietary notices as they appear on this Website.</p>
                                <p>Subject to these Terms, we also grant you a limited, personal, non-exclusive, non-transferable license to download, install and operate any plug-ins, software, information, or other content that we may have specifically identified within the Website as available for download solely in connection with accessing the Website, including, but not limited to, relevant MD REP TIME browser extensions (“Downloadable Tools”). Such Downloadable Tools are also subject to the additional terms provided to you upon download, including without limitation our End User License Agreement.</p>
                                <p>Our Website is not intended for and may not be used by individuals under 18 years of age. By registering for a MD REP TIME account, you state that you are at least 18 years of age, and you are responsible for ensuring that all MD REP TIME Users and Invitees are at least 18 years old. Creating an account with false information is a violation of our Terms, including creating an account on behalf of others or persons under the age of 18.</p>
                                <h4>EDUCATIONAL USE</h4>
                                <p>Children under the age of 18 shall only use the Services under an account created by and under their parent/guardian or school/educator and are specifically prohibited from the use of the Services otherwise. If You are a school or educator in the United States and want your students to use the Services, Customer is and shall be responsible for complying with the U.S. Family Educational Rights and Privacy Act (\"FERPA\") and Children’s Online Privacy Protection Act of 1998 and its rules (collectively, “COPPA”).</p>
                                <p>To the extent that MD REP TIME has access to “education records,” as defined by the Family Educational Rights & Privacy Acts of 1974 and its implementing regulations (“FERPA”), it is deemed and shall function as a “school official” with “legitimate educational interests” when fulfilling its responsibilities under this Agreement, and both parties agree that you have “direct control” over the use of “education records” as these terms are defined under FERPA. MD REP TIME agrees to comply with its obligations under FERPA, including but not limited to the limitations on re-disclosure of personally identifiable information from education records set forth in FERPA and with the terms set forth below.</p>
                                <p>This means you shall notify those students' parents/guardians of the personally identifiable information that it will collect and share with us and obtain parental/guardian consent before its students sign up or use the Services. When obtaining such consent, you shall provide parents/guardians with a copy of our Privacy Policies, including our FERPA and COPPA Privacy Policy. You must keep all consents on file and provide them to us if we request them. Additionally, you shall be responsible for verifying the student parent relationship and shall be responsible for compliance with the right of a parent to review personal information provided by the child. You shall comply with such requirements by requesting and providing MD REP TIME with a data subject request for the aforementioned data, or any changes to such data requested by the parent, and providing the data to the parent after verification of the student parent relationship. If you are located outside of the United States, MD REP TIME shall rely upon you and you shall obtain any required consents or approvals from the parent or guardian of any student covered by similar laws and, as a condition to your and your students' use of the Services, you shall comply with such laws.</p>
                                <h4>ACCOUNT SETUP</h4>
                                <p>To use the Website, you need to set up a MD REP TIME account. You may establish either a free account (“Free Account”) or a paid account (“Paid Account”). You are authorized by MD REP TIME to set up one Free Account only. MD REP TIME reserves the right to terminate any additional Free Accounts set up by you and any Free Accounts that have been inactive for over 6 months.</p>
                                <p>When you create an account, we collect registration-related information, which includes your email address and your name. Once you submit the required registration information, we alone will determine whether or not to approve your proposed account. If approved, you will be sent an email detailing how to complete your registration. For so long as you use the account, you agree to provide true, accurate, current, and complete information that can be accomplished by logging into your account and making relevant changes directly. You are responsible for complying with these Terms when you access this Website, whether directly or through any account that you may set up through or on this Website. Because it is your account, it is your job to obtain and maintain all equipment and services needed for access to and use of this Website as well as paying related charges. You agree to choose a strong and secure password(s) and maintain the confidentiality of your password(s), including any password of a third-party site that we may allow you to use to access this Website. Should you believe your password or security for this Website has been breached in any way, you must immediately notify us at <a href=\"mailto:support@mdreptime.com\">support@mdreptime.com</a>.</p>
                                <p>MD REP TIME or our billing processors collect your billing information when you upgrade to a Paid Account. All information is protected in accordance with our Privacy Policy.</p>
                                <p>Your account belongs to you. However, MD REP TIME controls the URL(s) assigned to your account and may change or deactivate the URL(s) without prior notice. If your account is paid for by another party for you to use (for example, paid and managed by your employer), the party paying for your account has the right to control it, manage it, and get reports on your use of the Paid Account. The party paying for your account does not have rights nor access to your separate, personal account(s) that are not paid for nor managed by that party.</p>
                                <h4>SUBSCRIPTION PERIOD AND SUBSCRIPTION FEES</h4>
                                <p>You agree to pay all applicable fees related to your use of this Website which are described fully on our pricing page. By providing a payment method, you expressly authorize us to charge the applicable fees on said payment method as well as taxes and other charges incurred thereto at regular intervals, all of which depend on your particular subscription and utilized services.</p>
                                <p>The subscription period for Paid Accounts can be month-to-month, yearly, or another duration described more fully on our pricing page.</p>
                                <p>Paid Accounts are subject to fees based upon the account type you've selected. For renewals, MD REP TIME will automatically charge your payment method in the amount of the then-current fee for your type of account, plus applicable taxes. All payments are non-refundable. To the extent that payment mechanisms are provided through third parties, you agree that MD REP TIME will have no liability to you arising out of the acts or omissions of such third parties. If applicable, you agree to maintain current billing information.</p>
                                <p>BY CREATING A PAID ACCOUNT, YOU CONSENT TO ALLOW MD REP TIME TO CHARGE YOUR PAYMENT METHOD, EITHER DIRECTLY OR THROUGH ITS PAYMENT PROCESSORS, FOR THE AMOUNTS DUE FOR YOUR INITIAL SUBSCRIPTION PERIOD AND FOR ADDITIONAL SUBSCRIPTION PERIODS UNTIL YOUR ACCOUNT IS CANCELED OR TERMINATED. PLEASE PRINT OUT THESE TERMS AND CONDITIONS FOR YOUR RECORDS.</p>
                                <h4>RENEWAL/CANCELLATION</h4>
                                <p>Paid Accounts will automatically renew for the same subscription period unless you cancel the account by the end of the then-current subscription period. You can cancel your account at any time by contacting customer service at <a href=\"mailto:support@mdreptime.com\">support@mdreptime.com</a>. Cancellation will be effective immediately. Please note that after you cancel your account, you may not be able to use or access the Platform and you will not be entitled to a refund of any fees that you've paid.</p>
                                <h4>LEGAL COMPLIANCE</h4>
                                <p>You agree to comply with all applicable domestic and international laws, statutes, ordinances, and regulations regarding your use of our Website. MD REP TIME reserves the right to investigate complaints or reported violations of our Terms and to take any action we deem appropriate, including but not limited to canceling your User account, reporting any suspected unlawful activity to law enforcement officials, regulators, or other third parties and disclosing any information necessary or appropriate to such persons or entities relating to your profile, e-mail addresses, usage history, posted materials, IP addresses, and traffic information, as allowed under our Privacy Policy. You agree to promptly notify MD REP TIME in the event that you are made aware of any unauthorized or illegal use of the Website.</p>
                                <h4>INTELLECTUAL PROPERTY</h4>
                                <p>Our Website may contain our service marks or trademarks as well as those of our affiliates or other companies, in the form of words, graphics, and logos. Your use of our Website does not constitute any right or license for you to use such service marks/trademarks. Our Website is also protected under international copyright laws. The copying, redistribution, use, or publication by you of any portion of our Website is strictly prohibited. Your use of our Website does not grant you ownership rights of any kind in our Website.</p>
                                <h4>NOTICES AND MESSAGE</h4>
                                <p>By using the Website, you consent to receive emails from us. These emails may include notices about applicable fees and charges, transactional information and other information concerning or related to this Website. These emails are part of your relationship with us. By scheduling a meeting as an Invitee with a MD REP TIME User, you consent to receive transactional emails related to the scheduled meeting (e.g. booking confirmations and reminders). If, as an Invitee, you provide your phone number for text reminders, you also consent to receive SMS text reminders from MD REP TIME related to the scheduled meeting between you and the MD REP TIME User.</p>
                                <p>You agree that any notices, agreements, disclosures, or other communications that we send you electronically will satisfy any legal communication requirements, including that such communications be in writing. You agree to keep your contact information up to date, and to monitor your email settings to ensure that you receive emails from us at your discretion and as necessary.</p>
                                <h4>LINKS TO OTHER WEBSITES</h4>
                                <p>Our Website may contain links to third party websites. These links are provided solely as a convenience to you. By linking to these websites, we do not create or have an affiliation with or sponsor such third party websites. The inclusion of links within our Website does not constitute any endorsement, guarantee, warranty, or recommendation of such third party websites. MD REP TIME has no control over the legal documents and privacy practices of third party websites, and by using them, you may be giving those third parties permission to use or control your information in ways MD REP TIME would not. As such, you access any third-party websites at your own risk.</p>
                                <h4>FORUMS</h4>
                                <p>Certain areas of this Website are public-facing and allow you to interact with others (e.g., the MD REP TIME blog and the idea portal) (together, “Forums”). These Forums may permit you to submit feedback, information, data, text, software, messages, or other materials (each, a \"Submission\"). We love hearing from our Users and Invitees! It's incredibly helpful and helps us to make a better MD REP TIME for all. If you choose to provide a Submission, either directly to us or via a Forum, you agree that we can use them without any restrictions or compensation to you.</p>
                                <p>Any information that you post in a Forum might be read, collected, and used by others who access it. To request removal of your information from a Forum, contact <a href=\"mailto:support@mdreptime.com\">support@mdreptime.com</a>. In some cases, we may not be able to remove your information, in which case we will let you know that, and why.</p>
                                <p>You agree that you are solely responsible for all of your Submissions and that any such Submissions are considered both non-confidential and non-proprietary. If you use Forums, you also understand that anyone could see your Submissions. MD REP TIME does not endorse, nor are we required to pre-screen your Submissions (although we might), and, like elsewhere on the Internet, Submissions from other people could offend you. Further, we do not guarantee that you will be able to edit or delete any Submission you have submitted.</p>
                                <p>By submitting any Submission, you are promising us that you own all rights in your Submission, your Submission does not infringe on the rights of others, your Submission does not violate any laws or regulations, and your Submission is not in poor taste.</p>
                                <p>You grant to us an irrevocable royalty-free license to copy, modify, publish and display your Submission, and to make, use (and permit others to use) your Submission for any purpose (including, without limitation, to use your Submission in our Website).</p>
                                <p>We are not obligated to publish any information or content on our Forum and can remove information or content at our sole discretion, with or without notice.</p>
                                <h4>UNAUTHORIZED ACTIVITIES</h4>
                                <p>To be clear, we authorize your use of this Website only for Permitted Purposes. Any other use of this Website beyond the Permitted Purposes is prohibited and, therefore, constitutes unauthorized use of this Website. This is because all rights to this Website remain our property.</p>
                                <p>Unauthorized use of this Website may result in the violation of various United States and international copyright laws, the deletion of your MD REP TIME account, or a block from the Website. Unless you have written permission from us stating otherwise, you are not authorized to use this Website in any of the following ways. (Note that these are examples only, and the list below is not a complete list of everything that you are not permitted to do):</p>
                                <p>You are not allowed to use the Website:</p>
                                <ul>
                                <li>In a manner that modifies, publicly displays, publicly performs, reproduces, or distributes any of this Website;</li>
                                <li>In a manner that violates any relevant law or the Terms of this agreement;</li>
                                <li>To stalk, harass, spam, or harm another individual, organization, or business;</li>
                                <li>To disclose information that you do not have permission to disclose;</li>
                                <li>To impersonate any person or entity, misstate your Personal Data, or otherwise misrepresent your affiliation with a person or entity;</li>
                                <li>To interfere with or disrupt this Website or servers or networks connected to this Website;</li>
                                <li>To use any data mining, robots, or similar data gathering or extraction methods in connection with this Website;</li>
                                <li>To disseminate any viruses, worms, or otherwise harmful code; or</li>
                                <li>To attempt to gain unauthorized access to any portion of this Website or any other accounts, computer systems, or networks connected to this Website, whether through hacking, password mining, or any other means;</li>
                                <li>To submit or store Payment Card Industry data (such as credit card numbers) without using an authorized MD REP TIME payment integration;</li>
                                <li>To disclose any types of information listed in California Customer Records statute (Cal. Civ. Code § 1798.80(e)) or other relevant privacy regulations, including medical or health insurance information, education information, employment information, credit or debit card information, or any other financial information, driver’s license, or other government identification number;</li>
                                <li>To disclose or collect any types of information considered to be protected classification characteristics under California or other relevant law, including Age (if 40 years or older), race, color, ancestry, national origin, citizenship, religion or creed, marital status, medical condition, physical or mental disability, sex (including gender, gender identity, gender expression, pregnancy or childbirth, and related medical conditions), sexual orientation, veteran or military status, and genetic information (including familial genetic information); and</li>
                                <li>To disclose or collect any information defined by relevant laws as biometric information, or any information that falls within the definition of “special categories of data” under EU Data Protection Laws, “protected health information” under California or other relevant law or regulations. “Special categories of data” include, for example, information about an individual’s race, ethnic origin, politics, religion, trade union membership, genetics, biometrics, health, sex life, sexual orientation, or criminal records.</li>
                                </ul>
                                <h4>INDEMNIFICATION</h4>
                                <p>You alone are responsible for any violation of these Terms by you. You agree to indemnify and hold MD REP TIME, its parents, subsidiaries, affiliates, officers, agents, employees, resellers or other partners, and licensors harmless from any claim, demand, loss, or damages, including reasonable attorneys’ fees, arising out of or related to Personal Data, or the use thereof, including but not limited to allegations that any processing of Personal Data by MD REP TIME and/or you under this Agreement violates any applicable law or regulation, or infringes the privacy or intellectual property rights of a third party, any content that you disclose to MD REP TIME via your use of the MD REP TIME Website, your use of the Website, your violation of these Terms, or your violation of any relevant law.</p>
                                <h4>INTELLECTUAL PROPERTY INFRINGEMENT</h4>
                                <p>We respect the intellectual property rights of others and encourage you to do the same. Accordingly, we have a policy of removing Submissions that violate intellectual property rights of others, suspending access to this Website (or any portion thereof) to any MD REP TIME User who uses this Website in violation of someone’s intellectual property rights, and/or terminating in appropriate circumstances the account of any MD REP TIME User who uses the Website in violation of someone’s intellectual property rights.</p>
                                <p>Pursuant to Title 17 of the United States Code, Section 512, we have implemented procedures for receiving written notification of claimed copyright infringement and for processing such claims in accordance with such law. If you believe your copyright or other intellectual property right is being infringed by a MD REP TIME User, please provide written notice to us for notice of claims of infringement at <a href=\"mailto:support@mdreptime.com\">support@mdreptime.com</a>.</p>
                                <p>To be sure the matter is handled immediately, your written notice must:</p>
                                <ul>
                                <li>Contain your physical or electronic signature;</li>
                                <li>Identify the copyrighted work or other intellectual property alleged to have been infringed;</li>
                                <li>Identify the allegedly infringing material in a sufficiently precise manner to allow us to locate that material;</li>
                                <li>Contain adequate information by which we can contact you (including postal address, telephone number, and e-mail address);</li>
                                <li>Contain a statement that you have a good faith belief that use of the copyrighted material or other intellectual property is not authorized by the owner, the owner's agent or the law;</li>
                                <li>Contain a statement that the information in the written notice is accurate; and</li>
                                <li>Contain a statement, under penalty of perjury, that you are authorized to act on behalf of the copyright or other intellectual property right owner.</li>
                                </ul>
                                <p>Unless the notice pertains to copyright or other intellectual property infringement, the Agent will be unable to address the listed concern.</p>
                                <p>We will notify you that we have removed or disabled access to copyright-protected material that you provided, if such removal is pursuant to a validly received Digital Millennium Copyright Act DMCA take-down notice. In response, you may provide our Agent with a written counter-notification that includes the following information:</p>
                                <ol>
                                <li>Your physical or electronic signature;</li>
                                <li>Identification of the material that has been removed or to which access has been disabled, and the location at which the material appeared before it was removed or access to it was disabled;</li>
                                <li>A statement from you under the penalty of perjury, that you have a good faith belief that the material was removed or disabled as a result of a mistake or misidentification of the material to be removed or disabled; and</li>
                                <li>Your name, physical address, and telephone number, and a statement that you consent to the jurisdiction of a court for the judicial district in which your physical address is located, or if your physical address is outside of the United States, for any judicial district in which we may be located, and that you will accept service of process from the person who provided notification of allegedly infringing material or an agent of such person.</li>
                                </ol>
                                <p>We reserve the right, in our sole discretion, to terminate the account or access of any MD REP TIME User or Invitee who is the subject of repeated DMCA or other infringement notifications.</p>
                                <h4>WARRANTY DISCLAIMER</h4>
                                <p>THE WEBSITE AND ALL CONTENT ARE PROVIDED \"AS IS\" AND \"WITH ALL FAULTS\" AND THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE IS WITH YOU. WE EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND (EXPRESS, IMPLIED OR STATUTORY) WHICH INCLUDES BUT IS NOT LIMITED TO, ANY IMPLIED OR STATUTORY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR USE OR PURPOSE, ACCURACY OF DATA, TITLE, AND NON-INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS.</p>
                                <p>THIS MEANS THAT WE DO NOT PROMISE YOU THAT THE WEBSITE IS FREE OF PROBLEMS. Without limiting the generality of the foregoing, we make no warranty that the Website will meet your requirements or will be uninterrupted, timely, secure, or error-free, or that defects will be corrected. We make no warranty as to the results that may be obtained or as to the accuracy or reliability of any information obtained through the Website. No advice or information, whether oral or written, obtained by you through the Website or from us or our subsidiaries/other affiliated companies will create any warranty. We disclaim all equitable indemnities.</p>
                                <h4>LIMITATION OF LIABILITY</h4>
                                <p>MD REP TIME WILL NOT BE LIABLE TO YOU OR OTHERS FOR ANY DAMAGES RESULTING FROM YOUR USE OF THE WEBSITE OR YOUR DISPLAYING, COPYING, OR DOWNLOADING ANY MATERIALS TO OR FROM THE WEBSITE. IN NO EVENT WILL MD REP TIME BE LIABLE TO YOU FOR ANY INDIRECT, EXTRAORDINARY, EXEMPLARY, PUNITIVE, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES (INCLUDING LOSS OF DATA, REVENUE, PROFITS, OPPORTUNITIES, REPUTATION, USE, OR OTHER ECONOMIC ADVANTAGE) HOWEVER ARISING, EVEN IF WE KNOW THERE IS A POSSIBILITY OF SUCH DAMAGE.</p>
                                <p>MD REP TIME’S MAXIMUM AGGREGATE LIABILITY TO YOU IN CONNECTION WITH THESE TERMS OR THE WEBSITE, REGARDLESS OF THE FORM OF ACTION (WHETHER SUCH LIABILITY ARISES DUE TO NEGLIGENCE, BREACH OF CONTRACT, MISREPRESENTATION, OR FOR ANY OTHER REASON), WILL AT ALL TIMES BE LIMITED TO THE GREATER OF (I) THE AMOUNT PAID, IF ANY, BY YOU TO MD REP TIME IN CONNECTION WITH THESE TERMS IN THE TWELVE (12) MONTHS PRIOR TO THE ACTION GIVING RISE TO LIABILITY OR (II) US $100.00.</p>
                                <p>THIS LIMITATION OF LIABILITY IS PART OF THE BASIS OF THE AGREEMENT BETWEEN YOU AND MD REP TIME AND SHALL APPLY TO ALL CLAIMS OF LIABILITY, EVEN IF MD REP TIME HAS BEEN TOLD OF THE POSSIBILITY OF ANY SUCH DAMAGE, AND EVEN IF THESE REMEDIES FAIL THEIR ESSENTIAL PURPOSE.</p>
                                <h4>LOCAL LAWS; EXPORT CONTROL</h4>
                                <p>We control and operate the Website from our headquarters in the United States of America and the entirety of the Website may not be appropriate or available for use in other locations. If you use the Website outside the United States of America, you are solely responsible for following applicable local laws.</p>
                                <p>MD REP TIME and you shall comply with all relevant United States export control laws and regulations. Without limiting the foregoing: (a) you acknowledge that the Website may be subject to the United States Export Administration Regulations; (b) you affirm that you are not, and you will not (i) permit MD REP TIME Users or Invitees to access or use the Website in a United States embargoed country; (ii) or permit MD REP TIME Users or Invitees on the U.S. Commerce Department’s Denied Persons, Entity, or Unverified Lists or (iii) permit MD REP TIME Users or Invitees on the U.S. Treasury Department’s list of Specially Designated Nationals and Consolidated Sanctions list; and (c) you are responsible for complying with any local laws and regulations which may impact your right to import, export, access, or use the Website.</p>
                                <h4>DISPUTE RESOLUTION AND ARBITRATION; CLASS ACTION WAIVER.</h4>
                                <h5>Please Read This Provision Carefully. It Affects Your Legal Rights.</h5>
                                <p>This provision facilitates the prompt and efficient resolution of any dispute that may arise between you and us. Effectively, then, “dispute” is given the broadest meaning enforceable by law and includes any claims against other parties relating to services or products provided or billed to you (such as our licensors, suppliers, dealers or third-party vendors) whenever you also assert claims against us in the same proceeding.</p>
                                <p>This provision provides that all disputes between you and us will be resolved by binding arbitration because acceptance of these Terms constitutes a waiver of your right to litigate claims and all opportunity to be heard by a judge or jury. We prefer this because we believe arbitration is less drama-filled than litigation. To be clear, there is no judge or jury in arbitration, and court review of an arbitration award is limited. The arbitrator must follow this agreement and can award the same damages and relief as a court (including attorney’s fees). YOU AND MD REP TIME AGREE THAT ANY AND ALL DISPUTES, AS DEFINED ABOVE, WHETHER PRESENTLY IN EXISTENCE OR BASED ON ACTS OR OMISSIONS IN THE PAST OR IN THE FUTURE, WILL BE RESOLVED EXCLUSIVELY AND FINALLY BY BINDING ARBITRATION RATHER THAN IN COURT IN ACCORDANCE WITH THIS PROVISION.</p>
                                <p><u>Pre-Arbitration Claim Resolution</u></p>
                                <p>For all disputes, you must first give us an opportunity to resolve the dispute which is first done by emailing us at <a href=\"mailto:support@mdreptime.com\">support@mdreptime.com</a> the following information: (1) your name, (2) your address, (3) a written description of your claim, and (4) a description of the specific relief you seek. If we do not resolve the dispute within 45 days after receiving your notification, then you may pursue your dispute in arbitration.</p>
                                <p><u>Arbitration Procedures</u></p>
                                <p>If this provision applies and the dispute is not resolved as provided above (Pre-Arbitration Claim Resolution) either you or we may initiate arbitration proceedings. JAMS, www.jamsadr.com, will arbitrate all disputes, and the arbitration will be conducted before a single arbitrator. The arbitration will be commenced as an individual arbitration, and will in no event be commenced as a class arbitration. This provision governs in the event it conflicts with the applicable arbitration rules. Under no circumstances will class action procedures or rules apply to the arbitration. Because this Website and these Terms concern interstate commerce, the Federal Arbitration Act (“FAA”) governs the arbitrability of all disputes. However, the arbitrator will apply applicable substantive law consistent with the FAA and the applicable statute of limitations or condition precedent to suit. You or we may initiate arbitration in either Georgia or the federal judicial district where you are located.</p>
                                <p><u>Class Action Waiver</u></p>
                                <p>Except as otherwise provided in this provision, the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of a class or representative proceeding or claims (such as a class action, consolidated action or private attorney general action) unless both you and MD REP TIME specifically agree to do so following initiation of the arbitration.</p>
                                <p><u>Other</u></p>
                                <p>You understand and agree that by accepting this provision in these Terms, you and we are each waiving the right to a jury trial or a trial before a judge in a public court. If any clause within this provision (other than the Class Action Waiver clause above) is found to be illegal or unenforceable, that clause will be severed from this provision whose remainder will be given full force and effect. If the Class Action Waiver clause is found to be illegal or unenforceable, this entire provision will be unenforceable and the dispute will be decided by a court. This provision will survive the termination of your account with us or our affiliates and your discontinued use of this Website. Notwithstanding any provision in this Agreement to the contrary, we agree that if we make any change to this provision (other than a change to the Notice Address), you may reject any such change and require us to adhere to the language in this provision if a dispute between us arises.</p>
                                <h4>GENERAL TERMS</h4>
                                <p>We think direct communication resolves most issues – if we feel that you are not complying with these Terms, we will likely tell you. We may even provide you with recommended necessary corrective action(s) if possible. However, certain violations of these Terms, as determined by us, may require immediate termination of your access to this Website without prior notice to you.</p>
                                <p>The Federal Arbitration Act, Georgia state law and applicable U.S. federal law, without regard to the choice or conflicts of law provisions, will govern these Terms to the fullest extent permitted by applicable law. Except for disputes subject to arbitration as described above, any disputes relating to these Terms or this Website will be heard in the courts located in Fulton County, Georgia. Except as otherwise set forth in the dispute resolution provision, if any of these Terms are deemed inconsistent with applicable law, then such term(s) will be interpreted to reflect the intentions of the parties, and no other terms will be modified. By choosing not to enforce any of these Terms, we are not waiving our rights. These Terms, together with our Privacy Notice, End User License Agreement, FERPA and COPPA Privacy Policy and Notice, and the Data Processing Addendum (as applicable), contain the entire agreement between you and us and, therefore, supersede all prior or contemporaneous negotiations, discussions or agreements between MD REP TIME and you about the Website and our services. Any definitions found in the Privacy Notice, End User License Agreement, FERPA and COPPA Privacy Policy and Notice, and Data Processing Addendum are hereby adopted by reference in this Agreement. The rights of MD REP TIME under our Terms will survive the termination of our Terms. No additional terms, conditions, consent, waiver, alteration, or modification shall be binding unless in writing and signed by both parties. Acceptance of any order by MD REP TIME is expressly limited to the terms and conditions of this Agreement. Any proposed additional or inconsistent terms or conditions, including those in or accompanying any Customer proposal, any Customer purchase order, or other agreement or any other Customer document issued in connection with the sale or delivery of Products or Services is deemed by MD REP TIME to be a material change and is objected to and rejected by MD REP TIME. MD REP TIME's acceptance of any orders will not constitute acceptance of any terms and conditions contained therein.</p>
                                <p>Neither You or MD REP TIME will be liable to the other for any delay or failure to perform any obligation under these Terms (except for a failure to pay fees) if the delay or failure is due to events which are beyond reasonable control, such as a strike, blockade, war, act of terrorism, riot, natural disaster, for failure, or diminishment of power or telecommunications or data networks or services.</p>
                                <p>Unless you have specifically notified MD REP TIME to the contrary in writing (including via email to <a href=\"mailto:support@mdreptime.com\">support@mdreptime.com</a>), MD REP TIME may disclose your company as a customer of MD REP TIME (if you use MD REP TIME for business purposes and/or use a business email address as your MD REP TIME User email address) and may use your company’s name and logo on the Website and in MD REP TIME’s promotional content. MD REP TIME will request your prior written consent for any other uses.</p>
                                <h4>CHANGES</h4>
                                <p>We may amend our Terms at any time by publishing revised Terms on our Website and/or by sending an email to the address you gave us. These Terms are current as of the Effective Date set forth above. If any changes are made to these Terms, we’ll post them on this page, so please be sure to check back periodically. If you continue to use MD REP TIME after those changes are in effect, you agree to the revised Terms. Therefore, it is important for you to periodically review our Terms to make sure you still agree to them. If you object to any such modifications, your sole recourse will be to cease using this Website. MD REP TIME reserves the right to change any and all features of our Website, at any time, without notice.</p>
                                <h4>CANADA</h4>
                                <p>The parties declare that they have required that these Terms and Conditions and all documents related hereto, either present or future, be drawn up in the English language only. Les parties déclarent par les présentes qu’elles exigent que cette entente et tous les documents y afferents, soit pour le present ou le future, soient rédigés en langue anglaise seulement.</p>
                                <h4>CONTACT US</h4>
                                <p>If you have any questions about these Terms or otherwise need to contact us for any reason, you can reach us at <a href=\"mailto:support@mdreptime.com\">support@mdreptime.com</a>.</p>",
            ]
        ];

        if(count($pages) !== 0) {
            foreach($pages as $page) {
                $_page = new Page;
                $_page->uuid = Str::uuid();
                $_page->user_id = $user->id;
                $_page->slug = unique_name('page', $page['title']);
                $_page->title = $page['title'];
                $_page->content = $page['content'];
                $_page->meta_robots = Page::DEFAULT_META_ROBOTS;
                $_page->template = Page::TEMPLATE_DEFAULT;
                $_page->status = Page::ACTIVE;
                $_page->visible = Page::VISIBLE;

                if($_page->save()) {
                    $site->assignPage($_page);
                }

                if(isset($page['image'])) {
                    if(filled($page['image'])) {
                        $_page->addMedia($page['image'])
                              ->preservingOriginal()
                              ->toMediaCollection('images');
                    }
                }
            }
        }
    }
}
